### ISSUE TITLE
Remove user management

### ISSUE THREAD

**Issue by M4tthewDE** [microtwitch/dukebot#2]
return to only me being able to use it

**Comment by NotNotQuinn** [comment]
I protest!!

**Comment by PaauullI** [comment]
same!

**Comment by M4tthewDE** [comment]
fixed 9510f81bd06662e9af03a636373bba9a6320418f

**Comment by NotNotQuinn** [comment]
![NOOO](https://cdn.7tv.app/emote/60c97197aa6b166bf186033a/4x)
